name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Run unit tests
        run: npm run test:unit
        
      - name: Run e2e test
        run: |
          docker-compose up
          npm run test:e2e
          docker-compose down

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: |
          railway up
          railway run npm run typeorm -- migration:run
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
